# Generated by Django 2.1.5 on 2019-01-30 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='imagen',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
