# Generated by Django 2.1.5 on 2019-01-30 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0002_comentario_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='imagen',
            field=models.ImageField(default='http://image10.bizrate-images.com/resize?sq=60&uid=2216744464', upload_to='media'),
        ),
    ]
