# Generated by Django 2.1.5 on 2019-02-07 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=200)),
                ('caratula', models.ImageField(upload_to='media')),
                ('costo', models.DecimalField(decimal_places=2, max_digits=3)),
                ('generos', models.ManyToManyField(related_name='GeneroPelicula', to='peliculas.Genero')),
            ],
        ),
        migrations.AddField(
            model_name='actor',
            name='peliculas',
            field=models.ManyToManyField(related_name='ActorPelicula', to='peliculas.Pelicula'),
        ),
    ]
