# Generated by Django 2.1.5 on 2019-02-07 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='costo',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
